# Supabase Session Pooler (IPv4-friendly)
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.rnrlwiocnhpwszranpqj
spring.datasource.password=Mgplayz3d!213

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000

# Supabase requires SSL
spring.datasource.hikari.data-source-properties.sslmode=require

server.port=8080